name: KICS PR
on:
  pull_request:
    branches:
      - main
jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: kics
        uses: Checkmarx/kics-github-action@v1.2
        with:
          # paths to a file or directories to scan, accepts a comma separated list
          path: terraform/aws/
          # defines which non-zero exit codes should be ignored (all, results, errors, none)
          ignore_on_exit: all
          output_formats: json
          output_path: cx.json
      - name: Expose report
        uses: actions/upload-artifact@v2
        with:
          name: kics results
          path: cx.json
