name: build
on:
  pull_request
jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: KICS Github Action
        uses: Checkmarx/kics-github-action@v1.2
        with:
          # paths to a file or directories to scan, accepts a comma separated list
          path: terraform/aws/
          # defines which non-zero exit codes should be ignored (all, results, errors, none)
